//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CvEducation
    {
        public int Id { get; set; }
        public string University { get; set; }
        public string DegreeProg { get; set; }
        public string Department { get; set; }
        public string Date { get; set; }
    }
}
