//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProject.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbEntityEntities : DbContext
    {
        public DbEntityEntities()
            : base("name=DbEntityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<CvAbout> CvAbout { get; set; }
        public virtual DbSet<CvContact> CvContact { get; set; }
        public virtual DbSet<CvEducation> CvEducation { get; set; }
        public virtual DbSet<CvLanguage> CvLanguage { get; set; }
        public virtual DbSet<CvSkills> CvSkills { get; set; }
        public virtual DbSet<CvSocialMedia> CvSocialMedia { get; set; }
    }
}
